name: Deploy Backend to Cloud Run

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: "read"
      id-token: "write"

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_SERVICE_KEY }}

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}

      - name: Decode and Save Firebase Credentials
        run: |
          echo "${{ secrets.FIREBASE_CREDENTIALS_B64 }}" | base64 --decode > firebase-credentials.json

      - name: Save GCP Service Key
        run: |
          echo "${{ secrets.GCP_SERVICE_KEY_B64 }}" | base64 --decode > gcp-key.json

      - name: Build and Push Docker Image
        run: |
          gcloud builds submit --tag gcr.io/${{ secrets.GCP_PROJECT_ID }}/soundwave-api

      - name: Deploy to Cloud Run
        run: |
          gcloud run deploy soundwave-api \
            --image gcr.io/${{ secrets.GCP_PROJECT_ID }}/soundwave-api \
            --platform managed \
            --region us-central1 \
            --allow-unauthenticated \
            --set-env-vars "CLIENT_ADDRESS=${{ secrets.CLIENT_ADDRESS }},FIREBASE_CREDENTIALS=${{ secrets.FIREBASE_CREDENTIALS_FILE }}"